### ISSUE TITLE
Bug with Tic-Tacs

### ISSUE THREAD

**Issue by QPCrummer** [WearBlackAllDay/DimensionalThreading#12] opened 2021-01-04 13:50 UTC
It allows for duplication of items and blocks!
https://github.com/Gegy/tic-tacs/issues/29

**Comment by KaptainWutax** [comment] 2021-01-05 00:43
Is there a mixin conflict?

**Comment by SnooComics9452** [comment] 2021-01-06 09:58
y i think should close this issue

**Closed** 2021-01-06 11:55 UTC

**Comment by DragonEggBedrockBreaking** [comment] 2021-01-26 14:03
cannot reproduce issue (noted already on tic tacs issue report)
(ik this is closed, I was just mentioning)
